# data
data:
  instruct_data: "/home/jovyan/mistral_codex_hack/data/train_data.jsonl"
  eval_instruct_data: "/home/jovyan/mistral_codex_hack/data/eval_data.jsonl"
# model
model_id_or_path: "/home/jovyan/home/jovyan/mistral_models/nemo"  # Change to downloaded path
lora:
  rank: 32

# optim
seq_len: 16384
batch_size: 1
max_steps: 1000
optim:
  lr: 6.e-5
  weight_decay: 0.1
  pct_start: 0.05

# other
seed: 0
log_freq: 1
eval_freq: 50
no_eval: False
ckpt_freq: 100

save_adapters: True  # save only trained LoRA adapters. Set to `False` to merge LoRA adapter into the base model and save full fine-tuned model

run_dir: "codex_hack"  # Fill

wandb:
  project: "codex_hackathon" # your wandb project name
  run_name: "codex_hackathon" # your wandb run name
  key: "" # your wandb api key
  offline: False
