# data
data:
  instruct_data: ""  # Fill
data:
  instruct_data: "/home/jovyan/mistral_codex_hack/data/ultrachat_chunk_train.jsonl"
  eval_instruct_data: "/home/jovyan/mistral_codex_hack/data/ultrachat_chunk_eval.jsonl"
# model
model_id_or_path: "/home/jovyan/home/jovyan/mistral_models/nemo"  # Change to downloaded path
lora:
  rank: 64

# optim
seq_len: 32768
batch_size: 1
max_steps: 300
optim:
  lr: 6.e-5
  weight_decay: 0.1
  pct_start: 0.05

# other
seed: 0
log_freq: 1
eval_freq: 100
no_eval: False
ckpt_freq: 100

save_adapters: True  # save only trained LoRA adapters. Set to `False` to merge LoRA adapter into the base model and save full fine-tuned model

run_dir: "codex_hack"  # Fill

wandb:
  project: "codex_hackathon" # your wandb project name
  run_name: "codex_hackathon" # your wandb run name
  key: "" # your wandb api key
  offline: False
